apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-extra-scrape-configs
  namespace: prometheus
data:
  nginx-scrape-configs.yaml: |
    - job_name: 'nginx'
      metrics_path: '/metrics'
      static_configs:
        - targets: ['nginx:80']
